config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
   @book = Book.new
   @books = Book.all
  end
  
  def show
   @book = Book.find(params[:id])
  end
  
  def create
   @book = Book.new(book_params)
   if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book)
   else
    @books = Book.all
    render :index
   end
  end

  def edit
   @book = Book.find(params[:id])
  end
  
  def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book)
   else
    @books = Book.all
    render :edit
   end
  end
  
  def destroy
   @book = Book.find(params[:id])
   @book.destroy
   flash[:notice] = "Book was successfully created."
   redirect_to books_path(@books)
  end
  
  private
  def book_params
   params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>
  <strong>Editing Book</strong>
</h1>
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors
 <ul>
   <% @book.errors.full_messages.each do |message| %>
    <il><%= message %></il>
   <% end %>
 </ul>
<% end %>
<%= form_with model: @book,url:book_path(@book.id),method: :patch do |f| %>
<div class ="filed">
 <h4>Title</h4>
  <%= f.text_field :title %>
</div>
<div class ="area">
 <h4>Body</h4>
  <%= f.text_area :body %>
</div>
 <div class ="submit">
  <%=f.submit'Update Book' %>
</div>
<% end %>

<%= link_to "Show",book_path(@book.id) %>
  |
<%= link_to "Back",books_path(@books) %>

app/views/books/index.html.erb
<body>
<div>
 <%= flash[:notice] %>
</div>
<h1>Books</h1>
<table>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan ="3"></th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show",book_path(book.id) %></td>
      <td><%= link_to "Edit",edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy",book_path(book.id),method: :delete,"data-confirm" => "Are you sure?" %></td>
    </tr>
    <% end %>
</table>


<h2>New Book</h2>
<% if @book.errors.any? %>
 <%= @book.errors.count %>errors
 <ul>
   <% @book.errors.full_messages.each do |message| %>
    <il><%= message %></il>
   <% end %>
 </ul>
<% end %>
<%= form_with model: @book,url: '/books',method: :post do |f| %>
<div class = "filed">
 <h4>Title</h4>
  <%= f.text_field :title %>
</div>
<div class ="area">
 <h4>Body</h4>
  <%= f.text_area :body %>
</div>
<div class ="submit">
  <%= f.submit 'Create Book' %>
</div>
 <% end %>
 </body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<body>
<div>
  <%= flash[:notice] %>
</div>
  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>
  <p>
    <strong>Body:</strong>
    <%= @book.body %>
  </p>

  <%= link_to "Edit",edit_book_path(@book.id) %>
   |
  <%= link_to "Back",books_path(@books) %>
</body>

app/views/homes/top.html.erb
<html>
  <body>
   <h1>
    ようこそ
    <strong>Bookers</strong>
    へ！
    </h1>
     <p>
       <strong>Bookers</strong>
        では、さまざまな書籍に関するあなたの意見や
     </p>
     <p>印象を共有し交換することができます</p>
     <p>
        <a href ="/books">start</a>
     </p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>